# === CALCOLATORE ===
server {
    listen 80;
    server_name calcolatore.artestramas3d.it;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name calcolatore.artestramas3d.it;

    ssl_certificate /etc/letsencrypt/live/calcolatore.artestramas3d.it/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/calcolatore.artestramas3d.it/privkey.pem;

    client_max_body_size 50M;

    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://backend:8001/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
